### PR TITLE
feat: add support for setting Decimal type precision and scale

### PR DESCRIPTION
**Pull request by khaledh**
We have the need to specify Decimal precision and scale, but sparkql is currently missing this. This PR adds this support.

### CODE REVIEW

**Comment by mattjw** [comment]
Thank you for the PR! I will take a look and cut a release soon.

**Comment by mattjw** [comment]
Looks like I just pushed to this branch on this fork. But didn't intend to – I was just toying around with something. 😅 So apologies for that. (Although the new commits are indeed valid.)

Almost done – should be able to follow up tomorrow.

**Review by mattjw — APPROVED** [review]
Thank you 👍.

I haven't used decimal types directly myself, so I've tried to expand the `examples/` with some examples. If you encounter any need for improvement in your own real use cases, let me know!

**Comment by mattjw** [comment]
@khaledh release `0.7.0` [published](https://pypi.org/project/sparkql/0.7.0/), which should have this change in it 🎊 . 

Sorry it almost took a week. The good news is that I fixed all the release automation for this project before I merged in your change. So that means this was release was successfully automated.

Future PRs can be entirely about the PR itself.

**Comment by khaledh** [comment]
@mattjw  Amazing! Thank you so much 🙇🏼

**Pull request merged**
